#!/bin/sh

set -e

case "$1" in

    remove|remove-in-favour|deconfigure|deconfigure-in-favour)

        if [ -x /etc/init.d/nginx ]; then
            if [ -x /usr/sbin/invoke-rc.d ] ; then
                   invoke-rc.d nginx stop
            else   
                   /etc/init.d/nginx stop
            fi
        fi

	if [ -x /usr/sbin/ngxdissite ]; then
	    ls /etc/nginx/sites-enabled/* | sed -e 's,/etc/nginx/sites-enabled/,,g' \
		| while read sitename
	    do
		/usr/sbin/ngxdissite $sitename
	    done
	fi

    ;;

    upgrade|failed-upgrade)

    ;;

    *)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

#DEBHELPER#

exit 0
